### ISSUE TITLE
Fake news datasets

### ISSUE THREAD

**Issue by diasdavid** [inesc-id/dclaims-pm#26]
- `A New Benchmark Dataset for Fake News Detection` https://arxiv.org/abs/1705.00648
- `Text & metadata from fake & biased news sources around the web` https://www.kaggle.com/mrisdal/fake-news
- Fake news challenge http://www.fakenewschallenge.org/ + https://github.com/FakeNewsChallenge

//cc @joaosantos15 @nuno-santos

**Comment by joaosantos15** [comment]
https://github.com/bs-detector/bs-detector
