### ISSUE TITLE
https://github.com/inesc-id/hypercerts-core need to be added to the HyperCerts team on the inesc-id Org

### ISSUE THREAD

**Issue by diasdavid** [inesc-id/dclaims-pm#31]
@miguelpardal podes ajudar com isto? //cc @nuno-santos

**Comment by diasdavid** [comment]
Alias, o que falta é admin perms

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1211152/35723551-8d6974a8-07af-11e8-93aa-e5e012aab714.png">

https://github.com/orgs/inesc-id/teams/dclaims/repositories

**Comment by diasdavid** [comment]
Entra em https://github.com/orgs/inesc-id/teams/dclaims/repositories e muda as perms de `Write` para `Admin`. Obrigado!

**Comment by miguelpardal** [comment]
Está feito.
